In [1]:
%pylab
from landlab import RasterModelGrid
from landlab.plot.imshow import imshow_node_grid
from landlab.components import PresFlowNetwork, MeltCreep
import numpy as np

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [2]:
mg = RasterModelGrid((20,30),100)
junc_elev = mg.add_zeros('node', 'junction__elevation')
#d_h = mg.add_ones('link', 'hydraulic__diameter')
d_h = np.random.rand(mg.number_of_links)
mg.add_field('link','hydraulic__diameter', d_h)
h = mg.add_zeros('node', 'hydraulic__head')
thickness = 500.*np.ones(mg.number_of_nodes)
Z = mg.add_field('node', 'ice__thickness', thickness)
#a = mg.add_ones('link', 'head_loss__exponent')
#f = mg.add_ones('link', 'friction__factor')
#h = np.random.rand(mg.number_of_nodes)
Q = mg.add_zeros('link', 'conduit__discharge')
#net_node_flux = mg.add_ones('node', 'net_node_flux', noclobber=False)
#set boundary node head

h[mg.nodes_at_left_edge] = 400.
h[mg.nodes_at_right_edge] = 300.
h[mg.nodes_at_top_edge] = 0.
h[mg.nodes_at_bottom_edge] = 0.
mg.set_closed_boundaries_at_grid_edges(False,True,False,True)
Q[mg.active_links] = 1.
n_core = mg.number_of_core_nodes
links = mg.links_at_node
print "Number of links = ", mg.number_of_links
print "Number of nodes = ", mg.number_of_nodes
print "Number of active links = ", mg.number_of_active_links
print "Number of core nodes = ", mg.number_of_core_nodes


Number of links =  1150
Number of nodes =  600
Number of active links =  998
Number of core nodes =  504


In [3]:

pfn = PresFlowNetwork(mg)


In [4]:
pfn.run_one_step()

Number of iterations = 1 tolerance = 1.36887369132
Number of iterations = 2 tolerance = 0.888593540729
Number of iterations = 3 tolerance = 0.647058295501
Number of iterations = 4 tolerance = 0.399166011301
Number of iterations = 5 tolerance = 0.256216798751
Number of iterations = 6 tolerance = 0.136147786004
Number of iterations = 7 tolerance = 0.0635313009835
Number of iterations = 8 tolerance = 0.0353598081
Number of iterations = 9 tolerance = 0.0202647525944
Number of iterations = 10 tolerance = 0.0140354543407
Number of iterations = 11 tolerance = 0.00747935940788
Number of iterations = 12 tolerance = 0.00388071504994
Number of iterations = 13 tolerance = 0.00175557331704
Number of iterations = 14 tolerance = 0.000855273204942


In [10]:
#figure()
#imshow_node_grid(mg, h)

In [4]:
mc = MeltCreep(mg, dt=1000.)

In [9]:
figure()
imshow_node_grid(mg, h)
nsteps = 500
for step in arange(nsteps):
    print "step =",step, " avg d_h=",mg.at_link['hydraulic__diameter'].mean()
    pfn.run_one_step()
    mc.run_one_step()
figure()
imshow_node_grid(mg, h)

step = 0  avg d_h= 10.0051879062
Number of iterations = 1 tolerance = 0.0342852722704
Number of iterations = 2 tolerance = 0.000604229403416
step = 1  avg d_h= 10.0965544916
Number of iterations = 1 tolerance = 0.0345623368471
Number of iterations = 2 tolerance = 0.000613864250837
step = 2  avg d_h= 10.189524204
Number of iterations = 1 tolerance = 0.0348434426734
Number of iterations = 2 tolerance = 0.000623719449947
step = 3  avg d_h= 10.2841395028
Number of iterations = 1 tolerance = 0.035128680519
Number of iterations = 2 tolerance = 0.000633801686116
step = 4  avg d_h= 10.3804443445
Number of iterations = 1 tolerance = 0.0354181398398
Number of iterations = 2 tolerance = 0.000644115922595
step = 5  avg d_h= 10.478484249
Number of iterations = 1 tolerance = 0.0357119134123
Number of iterations = 2 tolerance = 0.000654668982095
step = 6  avg d_h= 10.5783063684
Number of iterations = 1 tolerance = 0.036010096871
Number of iterations = 2 tolerance = 0.000665468087863
step = 7  avg d_h

/home/mcoving/anaconda2/lib/python2.7/site-packages/scipy/sparse/linalg/dsolve/linsolve.py:161: MatrixRankWarning: Matrix is exactly singular
  warn("Matrix is exactly singular", MatrixRankWarning)


Number of iterations = 1 tolerance = nan
step = 154  avg d_h= nan
Number of iterations = 1 tolerance = nan
step = 155  avg d_h= nan
Number of iterations = 1 tolerance = nan
step = 156  avg d_h= nan
Number of iterations = 1 tolerance = nan
step = 157  avg d_h= nan
Number of iterations = 1 tolerance = nan
step = 158  avg d_h= nan
Number of iterations = 1 tolerance = nan
step = 159  avg d_h= nan
Number of iterations = 1 tolerance = nan
step = 160  avg d_h= nan
Number of iterations = 1 tolerance = nan
step = 161  avg d_h= nan
Number of iterations = 1 tolerance = nan
step = 162  avg d_h= nan
Number of iterations = 1 tolerance = nan
step = 163  avg d_h= nan
Number of iterations = 1 tolerance = nan
step = 164  avg d_h= nan
Number of iterations = 1 tolerance = nan
step = 165  avg d_h= nan
Number of iterations = 1 tolerance = nan
step = 166  avg d_h= nan
Number of iterations = 1 tolerance = nan
step = 167  avg d_h= nan
Number of iterations = 1 tolerance = nan
step = 168  avg d_h= nan
Number of 

KeyboardInterrupt: 

NameError: name 'mean' is not defined

In [8]:
mc.creep.mean()

AttributeError: 'MeltCreep' object has no attribute 'creep'

In [25]:
print mc.d_h.mean()
print mg.at_link['hydraulic__diameter'].mean()

75.5638520587
75.5638520587


In [26]:
mc.run_one_step()

#mc._grid.at_link['hydraulic__diameter']

melt =  [ 0.  0.  0. ...,  0.  0.  0.]
creep =  [  7.40309628e-06   7.05020338e-06   7.28544012e-06 ...,   1.19620283e-05
   1.25493431e-05   4.69801322e-06]
mean ddh =  -0.233651019529


In [17]:
mg.at_link['hydraulic__diameter']

array([-0.55447622, -0.13331862, -0.41216245, ..., -0.38514875,
       -0.13794368, -0.61310949])

In [7]:
mg.active_links

array([  99,  100,  101, ..., 1828, 1829, 1830])

In [8]:
mg.at_link['hydraulic__diameter']

array([ 0.80235261,  0.49316923,  0.94300751, ...,  0.29808259,
        0.32525564,  0.05623906])